name: CI/CD Workflow

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
# –¢—É—Ç –∑–∞–º–µ–Ω–∏—Ç—å —à–∞–≥–∏ –ù–æ–¥–∞ –Ω–∞ –ø–∏—Ç–æ–Ω. –í—ã–±–∏—Ä–∞–µ–º –¥–∂–æ–±—ã –≤ —ç–∫—à–∏–Ω–∞—Ö –ø—Ä–æ–µ–∫—Ç–∞ –Ω–∞ –≥–∏—Ç—Ö–∞–±–µ,
# –º–µ—Ä–∂–∏–º –∏ —Ä–∞–∑–±–∏—Ä–∞–µ–º –∫–æ–Ω—Ñ–ª–∏–∫—Ç —Å–æ–µ–¥–∏–Ω—è—è –¥–≤–∞ —Ñ–∞–π–ª–∞
#      - name: Set up Node.js
#        uses: actions/setup-node@v3
#        with:
#          node-version: 20
#
#      - name: Install dependencies
#        run: npm install

# my-app  —ç—Ç–æ –Ω–∞–∑–≤–∞–Ω–∏–µ –¥–æ–∫–µ—Ä –æ–±—Ä–∞–∑–∞ –Ω–∞ –¥–æ–∫–µ—Ä —Ö–∞–±
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest .

      - name: Login to Docker Hub
        run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin

      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest

      - name: ‚úÖ Image pushed to Docker
        run: echo "Image pushed to Docker Hub!"

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest
            docker stop myapp || true && docker rm myapp || true
            docker run -d --name myapp -p 8080:3000 ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest

      - name: üéâ Done
        run: echo "Workflow is done"